services:
  flask_app:
    container_name: flask_app
    image: francescoxx/flask_live_app:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      # Host ở đây phải khớp hoàn toàn với tên service bên dưới
      - DB_URL=postgresql://tasdus:11072005@flask_db:5432/employee_db
    depends_on:
      - flask_db

  flask_db:
    container_name: flask_db
    image: postgres:12
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=11072005
      - POSTGRES_USER=tasdus
      - POSTGRES_DB=employee_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: # Thêm phần này để Flask chờ DB
      test: ["CMD-SHELL", "pg_isready -U tasdus -d employee_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata: {}